### ISSUE TITLE
Create Grafana dashboard for CloudWatch metrics

### ISSUE THREAD

**Issue by calvinnhieu** [HumanCellAtlas/matrix-service#105]
TODO: define which metrics should be captured

**Comment by parthshahva** [comment]
- Read/write on dynamo tables
- API response code breakdown
- Batch latency
- Size of batch queues
- Invocation and Failure count for each daemon lambda
- Invocation and Failure count for api lambda
- Average and max duration for each daemon lambda
- Failed requests (use dynamo state table to figure this out)
- Number of cache hits vs misses (Will figure out how to measure this after caching goes in)
- Average time from initial post request to completed job (Not sure how to measure this yet)

@mckinsel @calvinnhieu comment here if there is anything else you think of to measure

**Comment by parthshahva** [comment]
MVP grafana dashboard for dev: https://metrics.dev.data.humancellatlas.org/d/matrix-dev/matrix-dev?refresh=1m&panelId=18&orgId=1&from=1543851434706&to=1543860895863

Left: publish custom cloudwatch metrics to measure job and batch stats (not available currently from cloudwatch metrics)

**Comment by parthshahva** [comment]
https://github.com/HumanCellAtlas/dcp-monitoring/pull/19 open for review and https://github.com/HumanCellAtlas/matrix-service/pull/163 is merged. Once #163 is promoted up through prod (integration currently in progress) and https://github.com/HumanCellAtlas/dcp-monitoring/pull/19 is merged in, this ticket can be marked as done. Estimate: EOD 11/10
