### ISSUE TITLE
Define Reliability Goals

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/matrix-service#116]
This ticket is for the purpose fo tracking the initial set of reliability goals for each component, reliability being defined as a combination of uptime and fault tolerance. Included would be tooling to track the state of each component and make measurements against the set goals.

**Comment by brianraymor** [comment]
@rhiananthony, @sampierson , @mweiden - *Reliability Goals* are not listed in [Technical Architecture and Operational Requirements for GA](https://docs.google.com/spreadsheets/d/1YsO3N5tJxhLQ6e7v5IBrjH22q9k8LwISXCG0Ntj-AlQ/edit#gid=0). Is this a duplicate for *Availability*? Is this intended to be an acceptance criteria in *Availability*?  Assigning back to Rhian for clarification.

**Comment by mweiden** [comment]
Yes, this should be merged with the availability goals mentioned in the spreadsheet. We are using different terms, but the concerns are the same.

**Comment by brianraymor** [comment]
Closing then.
