### ISSUE TITLE
Flesh out matrix service documentation requirements

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/matrix-service#126]
- [ ] Restore [Motivation](https://github.com/HumanCellAtlas/matrix-service/pull/25)
- [ ] Add User Stories
- [ ] Add Matrix Schema for Zarr format
- [ ] Document each file conversion format _packaging_
- [ ] Create a Read The Docs (RTD) for Matrix Service
    - [ ] Generate codebase documentation in RTD
    - [ ] Add contextual (technical) documentation to RTD

**Comment by parthshahva** [comment]
https://docs.google.com/spreadsheets/d/1YGA34Gp2TiNzPRAaOFHLZ6h1IJA5QStQQKga_6fOOpk/edit?ts=5b69a09c#gid=0

**Comment by brianraymor** [comment]
Discussed. We'll re-open if the Swagger docs and vignettes do not meet developer needs.
