### ISSUE TITLE
DSS/Matrix interaction improvement

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/matrix-service#131]
Currently, the interaction between DSS and the Matrix Service is the most fragile part of the system. We are not well protected against dss issues or latency.  Zarr stores for 1 billion cells will only take up 4 tb according to @mckinsel.  We have some options here:

1) Register a subscription against dss and maintain our own copy of zarr stores. Issues here on how to handle updates and deletes

2) Dig directly into s3 rather than going via dss since we share the same aws account (icky)

Action item: Schedule 1 hour design session to discuss prototypes we can build

**Comment by brianraymor** [comment]
Not required for the refactored architecture.
