### ISSUE TITLE
Profile memory utilization of worker daemon

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/matrix-service#139]
Currently, the worker daemon is set to utilize 3gb of memory. Regardless of how much memory is actually utilized, AWS will charge us for the full memory reservation. We should profile the worker daemon to investigate why this high memory limit is required. There are some python tools that can help us here. We should also dig into the logs to see what the distribution of memory usage is historically (lambda logs output this in the last line of each invocation). 

Requirement for done: Either we fix the issue and reduce memory utilization or record why we need to maintain this limit of 3gb

**Comment by mckinsel** [comment]
I believe this is now more or less a canned query in Cloudwatch Logs Insights.

**Comment by parthshahva** [comment]
Running logs on cloudwatch insights indicates that the max memory used in Prod worker 1784mb and 
1895mb over the last 4 weeks. @mckinsel @calvinnhieu  any complaints if I bump us down to 2000mb from 2861mb?

**Comment by calvinnhieu** [comment]
Sure, to save costs over the holidays? I anticipate we'll have to play around with that value when we start processing 10x bundles in the new year.

**Comment by parthshahva** [comment]
It's not necessarily just to save costs over the holidays. It's not even that much money at our current request rate. There's just no need to over provision though if we're not using it

**Comment by calvinnhieu** [comment]
I see, and that sounds good. Thanks for looking into this

**Comment by mckinsel** [comment]
No problem, but I suspect we'll have to crank it right back up with the first 10x bundle.
