### ISSUE TITLE
Missing RequestHash in Mapper when using fake bundle IDs

### ISSUE THREAD

**Issue by calvinnhieu** [HumanCellAtlas/matrix-service#149]
https://humancellatlas.airbrake.io/projects/179579/groups/2357671779982880945?tab=overview

- Dynamo errors out looking for the RequestHash in the Mapper
- Only occurs _sometimes_ during functional tests for the following `bundle_fqids` inputs:
    - [`00000000-0000-0000-0000-000000000000.version`]
    - [`bundle1.version`, `bundle2.version`]

**Comment by brianraymor** [comment]
Not required for the refactored architecture.
