### ISSUE TITLE
Add query to return an array of matrix file formats

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#158]
Clients with rich UI such a the Data Browser would like to query the Matrix Service for supported file formats which can then dynamically populate related UI elements (_Select a File Format_):

<img width="479" alt="screen shot 2018-12-04 at 11 55 34 am" src="https://user-images.githubusercontent.com/3644743/49469141-9543e580-f7bb-11e8-8b93-4028abcf2ea3.png">

Otherwise, the Data Browser has to be informed for each new format offered by the Matrix Service and then hard-code which is not optimal. This also provides more flexibility for the Matrix Service if we decide to deprecate a format.

*Swagger-y Sketch:*

```
definitions:
  ...
  MatrixFileFormats:
    type: array
    items:
      type: string

paths:
 ...
  /matrix/formats:
    get:
      summary: "Return supported file formats"
      description: "Return the list of matrix file formats
      that can be requested by a consumer"
      tags:
        - API
      responses:
        "200":
          description: "Success"
          schema:
            $ref: '#/definitions/MatrixFileFormats'
```

```

**Comment by calvinnhieu** [comment]
https://github.com/HumanCellAtlas/matrix-service/pull/160
