### ISSUE TITLE
Explore alternatives to DynamoDB implementation

### ISSUE THREAD

**Issue by calvinnhieu** [HumanCellAtlas/matrix-service#159]
Currently, DynamoDB Tables are used to 1) track the distributed state of Lambdas (state table) and 2) implement a distributed lock mechanism (Lock table). This spike captures the time to investigate alternative solutions to these implementations.

Definition of Done
- [ ] Proposed alternate designs to replace (1) if any
    - [ ] If checked above, new issues created to capture this work
- [ ] Proposed alternate designs to replace (2) if any
    - [ ] If checked above, new issues created to capture this work

**Comment by brianraymor** [comment]
Not required for the refactored architecture.
