### ISSUE TITLE
Add filename parameter to POST /matrix endpoint

### ISSUE THREAD

**Issue by calvinnhieu** [HumanCellAtlas/matrix-service#162]
To support Data Portal client specified output filename(s)

Definition of Done:
- [ ] POST accepts filename parameter
- [ ] If supplied, the matrix_location value returned in GET /matrix reflects the filename input value

**Comment by brianraymor** [comment]
Based on our conversation at the matrix service meeting today, we need a _spike_ to explore the potential impact (caching, collisions) of this change. It seems trivial, but may not be.

**Comment by calvinnhieu** [comment]
After [investigation](https://github.com/HumanCellAtlas/matrix-service/blob/master/docs/filename_parameter.md), we have decided not to implement this feature. Implementing a filename parameter would require storing duplicates, one for each cached filename, and would significantly complicate the architecture. To resolve [issue](https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-browser/385), a Save As option client side may be sufficient.
