### ISSUE TITLE
Operator Documentation (RunBooks)

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#164]
- [x] Document deployment process in GitLab wiki: https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/matrix-service/wikis/Deployment-Runbooks

**Comment by rhiananthony** [comment]
This is a Q3 priotity, can we please move this out of the ice box, set a milestone (Q3 milestone 3?) and set an owner?

**Comment by brianraymor** [comment]
Yes - we will be reviewing new issues this afternoon.
