### ISSUE TITLE
Update matrix schema specification (zarr) to handle isoform data and raw counts

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#166]
Per team discussion on 12/10, moving https://github.com/HumanCellAtlas/secondary-analysis/issues/465 and the matrix schema specification to the matrix-service repo. 

Presently, the matrix output spec has one array called expression. For SS2, that contains gene TPM values. But, the matrix service is supposed to allow users to request raw counts and isoform counts when the assay type supports that. So, the spec needs to updated to included multiple arrays for different data types.

**Comment by kbergin** [comment]
Hi Brian! the corresponding ticket in Secondary Analysis backlog linked here is closed - maybe this ticket is done?
