### ISSUE TITLE
Issues with csv download

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#167]
When unzipped:

1. What is the rationale for two levels of subdirectories - `./tmp/tmpx5k4bgls/matrix.csv.zip`?
2. `matrix.csv.zip` should be named `matrix.csv`
3. This should be consistent with the .mtx directory structure - `./matrix`

Why was this not detected during testing?

**Comment by NoopDog** [comment]
Is this deployed to prod? I am still seeing this behavior for example with this project:
https://prod.data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22%3A%22project%22%2C%22terms%22%3A%5B%22Single+cell+transcriptome+analysis+of+human+pancreas%22%5D%7D%2C%7B%22facetName%22%3A%22fileFormat%22%2C%22terms%22%3A%5B%22matrix%22%5D%7D%5D

**Comment by brianraymor** [comment]
@NoopDog clarified that he's seeing both cases. Reproducible with: https://prod.data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22%3A%22project%22%2C%22terms%22%3A%5B%22Single+cell+transcriptome+analysis+of+human+pancreas%22%5D%7D%2C%7B%22facetName%22%3A%22fileFormat%22%2C%22terms%22%3A%5B%22matrix%22%5D%7D%5D

**Comment by brianraymor** [comment]
This appears to have been related to a failure to invalidate the cache after addressing this original issue.
