### ISSUE TITLE
Gene ids OR gene names option

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/matrix-service#169]
Hi Matrix Service - we were recalling today that when Genevieve was working on her vignette she had wanted the matrices she got to have gene names instead of gene ids. We were discussing, and we would like to keep the outputs from the pipelines as granular as possible, and the IDs are the best way to do that. However, it was suggested that maybe the matrix service could give the user the option to output gene names instead, based off of the gtf files used to generate the matrix. This could become especially easy to keep consistent and up to date when our concept of having reference bundles in the data store and the provenance of using such in analyses stored in the metadata comes to fruition. So until then, this is mostly a feature idea.

Would love to hear your thoughts!

**Comment by brianraymor** [comment]
Both _featurekey_ and _featurename_ are included in the latest matrix+metadata.

For example:

ENSG00000000003 | TSPAN6
