### ISSUE TITLE
Expectations for mtx: cells by columns instead of cells by row

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#170]
As shared on [**the_matrix_reloaded**](https://humancellatlas.slack.com/archives/CC9AR11T7/p1544691411075700):

_Just playing with getting  data into Seurat and discovered that the .mtx has cells by row, while Seurat’s (I’m using 2.3.4) Read10X() for example expects cells by column, and consequently fails. I understand the wider reasons for having cells by row, but just FYI the tools might not be expecting it._

.mtx is closely associated with cellranger/10X:
- [How is the MEX format used for ... matrices](https://kb.10xgenomics.com/hc/en-us/articles/115000794686-How-is-the-MEX-format-used-for-the-gene-barcode-matrices-)
- [Feature-Barcode matrices](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/matrices)

As a result, there are read10X _convenience_ functions and vignettes for Seurat and EdgeR based on this expectation.

This could be partially mitigated by clearly documenting the DCP matrix file formats which is in progress.

**Comment by mckinsel** [comment]
Perhaps a more general solution: rather than selecting "formats", users should select the tool they want to use. So the list would be "scanpy", "seurat", "SingleCellExperiment", etc.
