### ISSUE TITLE
Availability monitoring and downtime alerting

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#177]
Address additional requirements in the [Add the System monitoring for production systems](https://github.com/HumanCellAtlas/dcp-community/pull/53) once approved.

In addition, see [Health check should return 503 status if any components are down](https://github.com/HumanCellAtlas/dcp/issues/248)

- [ ] Level 2 healthcheck
- [ ] Updated grafana dashboard

**Comment by brianraymor** [comment]
This is our issue for tracking Availability which will be added to an Operational epic in the _dcp_ repo when defined by Technical Architecture.

**Comment by parthshahva** [comment]
Task left: Add level 2 health check
