### ISSUE TITLE
MVP for improved metadata access

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#189]
Per the request in the email thread _Formation of design team for creating a short term solution for our metadata access issues_:

_Here is a summary of the preparation we will need to complete before we can put the examples in front of users:_
_a. Prepare a TSV file for the each project - AI Simon_
_**b. Prepare a matrix file output for each project complete with metadata - AI Marcus**_
_c. Adrienne and Gabby to put this in front of Beta 1 users_

**Comment by mckinsel** [comment]
The files are in s3://hca-beta-demo-matrices
