### ISSUE TITLE
Stop using the deprecated Azul manifest endpoint

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/matrix-service#198]
There's a new manifest endpoint which the matrix service should be using (@hannes to elaborate).

**Comment by brianraymor** [comment]
@calvinnhieu to follow up with @hannes-ucsc for details.

**Comment by calvinnhieu** [comment]
Followed up with @hannes-ucsc - the new endpoint uses 301 redirects. Matrix will need to update to honor 301s with retries.

**Comment by hannes-ucsc** [comment]
… with retries and `Retry-After`.

**Comment by parthshahva** [comment]
@hannes-ucsc How long can this retry loop take? I'm seeing failures even after setting up exponential backoff and retrying on 301?

**Comment by hannes-ucsc** [comment]
@parthshahva 4min, today on production for a manifest with no filters applied. You should not apply exponential back-off and instead trust the Retry-After header. Please make sure to use the new endpoint: `/manifest/files (for 301/302 status code with `Retry-After` and `Location` response headers) or `/fetch/manifest/files` for a Javascript-friendly version that sends those three things as a JSON body in a 200 response.

**Comment by hannes-ucsc** [comment]
@parthshahva, before I forget, it just occurred to me that we should ask the Data Browser team to handle the manifest request retry loop client side. That way we wouldn't waste server side resources and could potentially offer better UI feedback (display "The matrix hand-off manifest is being prepared …" and then "The Matrix is being prepared …"). What do you think?

@NoopDog, this would be the same as what you do for the Terra hand-off today.

**Comment by parthshahva** [comment]
@hannes-ucsc Would this mean that the data browser keeps retrying on the manifest url and then passes the manifest url to matrix service once successful? I'm assuming that once it is generated it is cached? How long is it cached for?

**Comment by hannes-ucsc** [comment]
@parthshahva 

> Would this mean that the data browser keeps retrying on the manifest url and then passes the manifest url to matrix service once successful?

Yes.

> How long is it cached for?

One day [at present](https://github.com/DataBiosphere/azul/blob/589a787be75b990be9f134945e7afa23c561b628/terraform/s3.tf.json.template.py#L17).

**Comment by theathorn** [comment]
See https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-browser/647.

**Comment by parthshahva** [comment]
Closing as data browser is handling this
