### ISSUE TITLE
[Spike] What type of filtering needs to be supported?

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/matrix-service#2]
One of the goals of the matrix service is to allow users to subset matrices that exist in the DCP. So you could imagine a user saying, "I only want expression data for cells that are high-quality" or "I only care about expression data for these twenty genes". For the matrix service MVP, we need to specify that concretely, so we need to know exactly what sorts of filtering should be exposed to the user.

AC:
List of and detailed descriptions of matrix filtering operations to be supported in the MVP.

**Comment by l5han** [comment]
https://docs.google.com/document/d/1vHf1shvxmmUsCrbNWb8ABrEcQma2GKcQTSoPYDZ5vhY/edit?usp=sharing
