### ISSUE TITLE
What values should the matrix service deliver?

### ISSUE THREAD

**Issue by mckinsel** [HumanCellAtlas/matrix-service#20]
There's been a lot of discussion around formats and APIs for expression matrices, but the values in the matrices actually represent is in fact still an open question.

There are some options:
- Raw counts - this puts the onus of normalization on the end user in a way that might be unexpected
- TPM/CPM/FPKM - picking one makes us pretty opinionated, and they're not all appropriate for all applications. Also, how would we update based on filtering and merging queries?

**Comment by TimothyTickle** [comment]
We did an informal survey and it seems a first offering could be:
10X - umi collapsed counts and/or CPM
SS2 raw counts and/or TPM

As a stretch people want the read-support underlying any UMI collapse (reads per UMI).

**Comment by brianraymor** [comment]
@ambrosejcarr - Could you update the status of this research and overall next steps to finalize?

**Comment by brianraymor** [comment]
**Proposed in 10/10 email to AWG**

_Unless we receive feedback, the following describes how we will deliver formats for SS2 and 10x during the Beta (Tier 2 testing period):_

_Target identifiers: Genes (not transcripts) from the GENCODE reference_

_Default expression formats:_ 
- _10x v2: raw counts_
- _SS2: tpm_
