### ISSUE TITLE
Deprecate ETA in matrix service get requests

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/matrix-service#202]
Per the thread in [_the_matrix_reloaded_](https://humancellatlas.slack.com/archives/CC9AR11T7/p1551292299003100)

- [ ] Method to determine ETA in new redshift/batch infrastructure is determined
- [ ] ETA is populated in get requests to the matrix service

**Comment by parthshahva** [comment]
Conversation from slack

Parth Shah [8:15 AM]
@Brian Raymor In order to provide an estimate, we will need the ability to do 4 things 1) investigate query queue length 2) estimate query runtime based on # of input bundles 3) investigate batch queue length 4) estimate conversion runtime based on # of cells. However, there is a chicken and egg problem here. We can't estimate cell # (ie conversion time) until the query completes. Also, batch scales up resources so ETA is not correlated with length of batch queue. Additionally, point 4 is dependent on Marcus' changes getting merged in so that we have new #s for conversion times

Parth Shah [8:17 AM]
I will add this comment to the ticket. But summary is that this needs to be discussed with team and granularity expected needs to be established

Calvin   [4 hours ago]
From a brief conversation I had with adrienne and dave, it sounds like a general indication of progress would be a good first step. Providing a percentage based on the state table is something we can consider. Considering all the variability with Batch cold starts and concurrent load, providing inaccurate time estimates might be a worse user experience than providing none at all (edited)

Parth Shah   [3 hours ago]
A percentage is also a poor experience if not correlated with time though.

Parth Shah   [3 hours ago]
I would prefer something like 5/8 steps completed rather than a percentage for optimal experience given various moving parts

**Comment by brianraymor** [comment]
Another option is to deprecate _ETA_ if we cannot calculate a meaningful value. Other DCP asynchronous API(s) like the [Query Service](https://query.staging.data.humancellatlas.org/) do not support this feature.

**Comment by brianraymor** [comment]
@theathorn and @NoopDog - after much review, we cannot find a solution that would return a meaningful ETA, so the matrix service cannot support this property.

@mckinsel and @calvinnhieu - what do you think about annotating as _deprecated_ so the swagger documentation is correct and we do not break the API with the data browser?

~~~
    v0_MatrixResponse:
      type: object
      properties:
        ...
        eta:
          type: string
          deprecated: true
~~~
![deprecated.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/3a259116-d031-4921-aacc-503040f5acb0)
