### ISSUE TITLE
Review HCA repositories and verify that the list of readers/writers is following principle of least access

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/matrix-service#213]
The HumanCellAtlas GitHub teams have been restructured.
To ease the transition to this structured world, everyone is currently in a team called "HCA" that has WRITE access to all repos.  We want to move away from this.

Each component team lead needs to audit the GitHub teams that have access to their repos.
Ensure only appropriate teams (e.g. CZI, UCSC, etc) have write access to your component's repos.
Ensure that you approve of any collaborators.
Then remove access from team HCA.

**Comment by stahiri** [comment]
@calvinnhieu - Believe you're the appropriate owner of this task so assigning to you; please reassign to someone else if you are not the correct person!

**Comment by parthshahva** [comment]
CZI assigned as owner of matrix service. Full access to HCA org has been revoked
