### ISSUE TITLE
Run queries in a safe manner

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/matrix-service#220]
Currently, we are loading queries into a private s3 bucket and storing a reference in sqs. Things to do:
- [ ] Setup prepared statements or investigate best practice for templating queries
- [ ] Driver should store params and which prepared statement to use in s3
- [x] Use read only user to execute queries from requests

**Comment by parthshahva** [comment]
cc @mweiden as this ticket is based on your suggestions. Free free to update or leave any additional comments

**Comment by mweiden** [comment]
@parthshahva looks good to me!

**Comment by parthshahva** [comment]
5/7 Update: Sticking with readonly user to ensure no non-select queries are run.

According to redshift documentation:
Prepared statements only last for the duration of the current session. When the session ends, the prepared statement is discarded, so it must be re-created before being used again. This also means that a single prepared statement can't be used by multiple simultaneous database clients; however, each client can create its own prepared statement to use. The prepared statement can be manually removed using the DEALLOCATE command.
