### ISSUE TITLE
Investigate how to ensure bundles are not silently dropped from output

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/matrix-service#221]
Questions:
1) What is the best way to maintain an "expected_cells" value for a request?
2) Should we return an error instead of serving matrix if cells do not match expected_cells count?
3) Should we ever be okay with dropping bundles from the output?

**Comment by mckinsel** [comment]
I think this is going to be pretty difficult, since we won't know what we don't know. But one thing that we could check is that the count of distinct cellkeys selected from the expression table matches the count of rows selected from the cell table.

**Comment by parthshahva** [comment]
Solution: compare count(*) on analysis to number of input bundles. Return error if there is a mismatch

**Comment by parthshahva** [comment]
@calvinnhieu would this query consistently return within ~15 seconds with short query acceleration in place?

**Comment by parthshahva** [comment]
Actually nevermind, this query is going to run in the driver so it has a lot longer (will increase driver lambda timeout to 15 minutes)
