### ISSUE TITLE
Metadata field naming is inconsistent between matrix and metadata schema, causing user confusion

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#226]
See [Insight 2](https://docs.google.com/document/d/1qg4aPddgy2SFFKAxvwfZJTM4xDNVN4OgFuf5dAGD3bU/edit#heading=h.w958cay3ryal)

@kozbo has updated the [Metadata Access Beta 2 plan](https://docs.google.com/document/d/1u2OOkqnKtVKUhg-yWowuUco_P-A4p8VBx0oAai7E8aU/edit#heading=h.ir65rvt4c7k2):

_AI Simon, **Calvin**, Hannes to generate TSV output for each project on prod to verify that the script handles all current projects. NOTE: Please work with the matrix team, the browser team and Mark D. to **standardize on field names**. Please review these [findings](https://docs.google.com/document/d/1qg4aPddgy2SFFKAxvwfZJTM4xDNVN4OgFuf5dAGD3bU/edit) from the Beta Team interviews._

**Comment by diekhans** [comment]
Each field in the metadata has a fully qualified name that is globally unique in metadata schema.

The purpose of the fully qualified name is to allow conversion between spreadsheets and structured data in json format. The fully qualified name is used in Simon's TSV.

@simonjupp can tell you how to obtain the mapping to the fully qualified name.

**Comment by simonjupp** [comment]
The best way is via the SchemaTemplate library that gets the fully qualified names through schema introspection. Example of how to use it are in this script.

https://github.com/HumanCellAtlas/ingest-client/blob/master/examples/template/schema_to_template.py

We're also integration the ability to support simple migration of field names using this library HumanCellAtlas/ingest-central#158

**Comment by kozbo** [comment]
It was decided in a phone meeting on Mar 22 that the Matrix Service (and others) would use fully qualified names for all fields in the metadata output. Also it is not necessary to include other fields as they will be available by joining with the larger TSV file being prepared for each project.
