### ISSUE TITLE
Metadata fields are missing from both the matrix and ‘general’ files.

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#228]
Review and respond with a position to [Insight 3](https://docs.google.com/document/d/1qg4aPddgy2SFFKAxvwfZJTM4xDNVN4OgFuf5dAGD3bU/edit#heading=h.rppmjswke1am)

_**Recommendation**: We should make sure metadata is as consistent and complete as possible between different formats.  If we decide to make matrix metadata a smaller set of all possible metadata, we need to alert users to this and direct them to the full metadata._

**Comment by kozbo** [comment]
It was decided in a phone meeting on Mar 22 that the Matrix Service (and others) would use fully qualified names for all fields in the metadata output. Also it is not necessary to include other fields as they will be available by joining with the larger TSV file being prepared for each project. 

There should be some basic information in the ReadMe generated by the Matrix Service that includes a reference to where to find more information on the metadata fields. We suggested a pointer to the metadata dictionary section on the portal. 

The portal will try to add search-ability to the dictionary to help the user understand the structure and meaning of fields.

We are also hoping to provide a consumer vignette as an example on how to code against the output from the Matrix service.

**Comment by brianraymor** [comment]
@mckinsel to update the pending README to include _a pointer to the metadata dictionary section on the portal._
