### ISSUE TITLE
Update initialize_request signature

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#239]
https://github.com/HumanCellAtlas/matrix-service/blob/master/matrix/lambdas/api/core.py#L63
~~~
    RequestTracker(request_id).initialize_request(format)
~~~

The *format* parameter is not consumed by [_initialize_request_](
https://github.com/HumanCellAtlas/matrix-service/blob/257ba6a96f43d95b9c820dc913b93b183e9b8102/matrix/common/request/request_tracker.py#L101).

Consider:
- [ ] Removing the parameter in the call to initialize_request
- [ ] Updating the signature of initialize_request

**Comment by parthshahva** [comment]
initialize_request does use fmt: https://github.com/HumanCellAtlas/matrix-service/blob/master/matrix/common/request/request_tracker.py#L141. I think you were looking at old code. I've updated the param to be included in the docstring
