### ISSUE TITLE
Conversion runs out of memory for 12k bundles/cells

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/matrix-service#243]

**Comment by brianraymor** [comment]
Memory use is down to 4 GB. Plan to merge.

**Comment by brianraymor** [comment]
April 30 meeting - Validate whether this is limited to loompy.

**Comment by brianraymor** [comment]
Update from Parth *csv completed: https://console.aws.amazon.com/s3/object/dcp-matrix-service-results-dev/403f3400-9805-426b-b485-5c8afb7b172e.csv.zip?region=us-east-1&tab=overview&prefixSearch=403f3400-9805-426b-b485-5c8afb7b172e. It took about a day
The second loom and mtx jobs succeeded as well(loom is consistently ~ 12 hours for full hca, mtx ~ 6 hours for full hca)*. We've agreed to create a Spike to research improvements in the performance of format conversion.
