### ISSUE TITLE
Update ETL to support optimus

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#268]
**Pending** 

[Update Schema Versions pipeline-tools](https://github.com/HumanCellAtlas/pipeline-tools/pull/142) pull request
**May 17** [Close on a decision](https://humancellatlas.slack.com/archives/G9XD6L0AD/p1554404987127500) about whether both cellranger **AND** optimus are supported.

And then:

- [x] Add a `parse_optimus` function in` transformers.py` based on the documented optimus outputs
- [ ] Update `load_redshift.py`

**Comment by mweiden** [comment]
cc @kbergin

**Comment by brianraymor** [comment]
Validating https://github.com/HumanCellAtlas/skylab/pull/224
