### ISSUE TITLE
Capture appropriate alerts and audit trails so we can handle detected attacks and understand the consequences of emergent threats and breaches

### ISSUE THREAD

**Issue by stahiri** [HumanCellAtlas/matrix-service#270]
As specified in the [Q2 Roadmap] (https://docs.google.com/spreadsheets/d/1iAL2JR3ndgMmYwojUU0kU8Pm7B7ycRLt_973seREd3M/edit#gid=1107068822&range=C10).

We need appropriate alerts and audit trails so we can learn about and appropriately handle detected attacks and understand the consequences of emergent threats and breaches. This includes being able to know when an attack is taking place and being able to see in the logs what the attack entailed (what attacker accessed, changed, etc.).

__Deliverable__:
Ensure each component captures audit logs for the following types of events (as appropriate):
• Server alerts and error messages
• User log-on and log-off (successful or unsuccessful)
• System administration activities
• Modification of privileges and access
• Modifications to the application
• Application alerts and error messages
• Configuration changes
• Account creation, modification, or deletion

**Comment by parthshahva** [comment]
I don't think we have any work here. Between cloudwatch logging, grafana monitoring, cloudtrail logging of all aws interactions, and lack of signing in to matrix service, it appears that all the deliverables are covered

**Comment by calvinnhieu** [comment]
Agree with @parthshahva with one consideration: _Application alerts_ may be improved by alerting developer whens unexpected failures occur to expedite triaging (e.g. Matrix request timed out or repeated failures). Below is a breakdown of all deliverables:

_Deliverable:_
_Ensure each component captures audit logs for the following types of events (as appropriate):_

_• Server alerts and error message_
-v1 health check in place, v2 health check in progress, alerts to #matrix-dev
-Server errors captured in Cloudwatch logs via AWS Lambda, Batch, ECS

_• User log-on and log-off (successful or unsuccessful)_
-Not applicable to Matrix Service

_• System administration activities_
-AWS CloudTrail Logs

_• Modification of privileges and access_
-AWS CloudTrail Logs

_• Modifications to the application_
-Git
-Deployment packages available in AWS Lambda, Batch, ECS, Docker 

_• Application alerts and error messages_
-Cloudwatch logs, Airbrake, Grafana dashboards
-Application errors stored in DynamoDB, visualized in Grafana, and propagated to users via GET /matrix

_• Configuration changes_
-Terraform, CloudTrail logs

_• Account creation, modification, or deletion_
- Not applicable to Matrix Service

**Comment by stahiri** [comment]
Thank you! Follow-up question: are these logs being aggregated in any one location?

**Comment by calvinnhieu** [comment]
Not that I'm aware of - put another way, CloudWatch Logs (application logs) and CloudTrail Logs (audit trails) are the raw sources of logging that are consumed by the other tools to inform the team via alerts/visualizations.

**Comment by stahiri** [comment]
Yep, got it - thanks!
