### ISSUE TITLE
HCA DCP Users can download Expression Matrices for 10X and SS2 Mouse data

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#279]
**Theme**: *Lay the groundwork for increasing the availability of analysis of new assays and species in the DCP*

[**Objective**](https://docs.google.com/spreadsheets/d/1iAL2JR3ndgMmYwojUU0kU8Pm7B7ycRLt_973seREd3M/edit#gid=1107068822): Users can submit and access processed model species (mouse) data for 10X and SS2.

[**August 6 - Guidance from AWG**](https://docs.google.com/document/d/1YcSg2DhePi1Ozb0ty7_pGdAPiPeN9B6WaDhuN0PiYRU/edit#heading=h.qf4cth7gazsu)

Consider a "give me all kidney cells" query: 
- Only return human kidney cells, mouse requires an explicit "from mouse" in the query
  - This assumes all queries are human by default.
  - This is the requested default for a query not specifying species.

 
- Return two matrices, one human and one mouse (generalizes to n matrices for chimp, zebrafish, fly, etc
  - If mouse is specified, this is the default behavior requested.

**Comment by ambrosejcarr** [comment]
@mckinsel the mouse reference used by both Optimus and SS2 is [ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M21/gencode.vM21.annotation.gtf.gz](ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M21/gencode.vM21.annotation.gtf.gz)

cc @kbergin @barkasn @kishorikonwar

**Comment by brianraymor** [comment]
Moving to Q3 M1 per the [schedule](https://github.com/HumanCellAtlas/dcp/issues/44#issuecomment-498410232) for the secondary analysis blocking issue.

**Comment by brianraymor** [comment]
Moving to Q3 M3 per the schedule for the secondary analysis blocking issue.

**Comment by brianraymor** [comment]
Update from Secondary Analysis: _We’ve prepared an SS2 mouse bundle in integration for matrix service testing. Please let me know if there are any issues with the bundle or anything else you need!_
```analysis bundle uuid    51d8eda8-bbd9-48ab-9ffc-00cf1cdef087
analysis bundle version 2019-08-05T141528.848170Z
primary bundle uuid     c6cb322a-3d63-4a0b-8440-533da4febc63
primary bundle version  2019-08-02T202139.757537Z```
