### ISSUE TITLE
Investigate improvements for concurrency

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#280]
- [x] Review [concurrency scaling](https://aws.amazon.com/blogs/aws/new-concurrency-scaling-for-amazon-redshift-peak-performance-at-all-times/) for Redshift

**Comment by calvinnhieu** [comment]
**Concurrency scaling:**
Redshift cluster and ECS query runner currently are not configured to scale resources with increased concurrent request load. Below are recommendations for scaling these services:

*Redshift:*
- Configure 2 [WLM queues](https://docs.aws.amazon.com/redshift/latest/dg/cm-c-defining-query-queues.html)
  1. c=10, [SQA enabled](https://docs.aws.amazon.com/redshift/latest/dg/wlm-short-query-acceleration.html), [concurrency scaling](https://docs.aws.amazon.com/redshift/latest/dg/concurrency-scaling.html) enabled for all read queries (i.e. matrix service request queries)
  2. c=5, for processing DSS notifications

Currently, one (default) WLM queue is configured to with a concurrency limit of 5. These changes will 1) provide a query processing queue that will automatically spin up cluster resources to process concurrent queries above c=10 and 2) provide a separate queue for processing DSS notifications (i.e. write operations). This separation is proposed (but not required) as only READ queries, not WRITE, are eligible for SQA and Concurrency Scaling.

*ECS Query Runner:*
- Parallelize message processing in `query_runner.py`
- Configure [ECS Auto Scaling](https://docs.aws.amazon.com/autoscaling/application/userguide/what-is-application-auto-scaling.html) according to CPU Utilization metrics ([Step Scaling Policy](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-autoscaling-stepscaling.html))

Currently, the Query Runner's concurrency is configurable via terraform, but is static wrt to request load. Adding parallelization to the current task implementation and enabling ECS Auto Scaling will allow this component to scale wrt to concurrent load.

**Comment by brianraymor** [comment]
**May 7** - Agreed to create a separate issue to research improving the performance of file conversion - #286. Matrix Team to also review any new requirements related to the the Filtering API (Listing permitted values) which should return immediately.

**Comment by calvinnhieu** [comment]
Opened an AWS support ticket to investigate issues with UNLOAD queries not activating concurrency scaling clusters.

https://console.aws.amazon.com/support/cases?region=us-east-1#/6082140911/en

From my call with AWS Support, this is unexpected behavior and concurrency scaling should be working for our use case. Waiting to hear back from their investigation.

The other option for scaling Redshift is Elastic Resize. This approach manually modifies the size of the cluster and requires a few minutes of downtime during resizing which is not ideal.
https://aws.amazon.com/blogs/big-data/scale-your-amazon-redshift-clusters-up-and-down-in-minutes-to-get-the-performance-you-need-when-you-need-it/

**Comment by calvinnhieu** [comment]
Per discussion in the above AWS support ticket, concurrency scaling support for UNLOAD queries was recently released in the latest Redshift version. We will move forward with the above proposed implementation configuring 2 WLM queues:

1. SQA and concurrency scaling for all READ queries (API queries)
2. SQA for all WRITE queries (DSS notifications)
