### ISSUE TITLE
unable to download file using the zarr format

### ISSUE THREAD

**Issue by dvantwisk** [HumanCellAtlas/matrix-service#289]
I am attempting to download the bundles:
```
980b814a-b493-4611-8157-c0193590e7d9.2018-11-12T131442.994059Z
7243c745-606d-4827-9fea-65a925d5ab98.2018-11-07T002256.653887Z
```

from the expression matrix service specifying the `matrix/format` as `zarr`. This gives me a 400 error. The README.md states that doing this should be possible https://github.com/HumanCellAtlas/matrix-service#file-formats but the swagger api doesn't seem to accept `zarr` is an option https://matrix.staging.data.humancellatlas.org/ :
```
bundle_fqids: | [...]
-- | --
bundle_fqids_url: | string ($url)
format: | string Enum:[ loom, csv, mtx ]
```

Does (or will) the expression matrix service provide zarr files?

Message me back if you need a more concrete example, as I am currently using `HCAMatrixBrowser` from Bioconductor to create the request.

**Comment by dvantwisk** [comment]
In addition, not adding to a `matrix/format` to the request body seems to give a `loom` file, not  `zarr` file.

**Comment by parthshahva** [comment]
@dvantwisk Apologies, the readme needs to be updated. The matrix service does not currently provide support for zarr file outputs and defaults to loom. cc @mckinsel @brianraymor

**Comment by dvantwisk** [comment]
Do you plan on adding the zarr format in the future?

**Comment by mckinsel** [comment]
Hey @dvantwisk , we don't currently have concrete plans to return zarr-formatted matrices. That said, if users ask for it, we can do it. Do you need them in bioconductor? I thought there wasn't much of an R interface to zarr.

**Comment by brianraymor** [comment]
See also @dvantwisk 's [A package to integrate the zarr format with Biocondcutor's Experiment class](https://github.com/Bioconductor/ZarrExperiment)

**Comment by dvantwisk** [comment]
We have found another way to do what we need to have done without zarr files, so it doesn’t seem like we need to be able to get them from the matrix service. Originally we were going to create a package for zarr, but it doesn't seem like it's needed for the time being and is being put on hold. I think this issue can be closed for now.
