### ISSUE TITLE
Add bundle/file uuids/versions to matrix metadata output

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/matrix-service#291]
To track the provenance of a matrix service output file we need to add 4 additional fields: bundle uuid, bundle version, file uuid, file version.
This would allow the user to correlate any matrix service output file back to the corresponding manifest.
The cell_suspension_id is not versioned and is therefore not sufficient.

**Comment by theathorn** [comment]
The 4 requested fields are for annotations per cell.

**Comment by brianraymor** [comment]
The comment in - https://github.com/HumanCellAtlas/data-browser/issues/568#issuecomment-491397967 - _The notion of file_uuid and file_version does not make sense for the matrix service. Information about a cell can be spread across multiple files_ needs further discussion.

**Comment by theathorn** [comment]
See https://humancellatlas.slack.com/archives/CD0PLMWJZ/p1559162674013700

**Comment by mckinsel** [comment]
Further see https://humancellatlas.slack.com/archives/CD0PLMWJZ/p1559925629008500

It turns out file uuids and versions are not available in the metadata tsv.

**Comment by brianraymor** [comment]
Trevor expects the blocking issue to be resolved by July 12.

**Comment by theathorn** [comment]
The tsvs in prod already havet the 2 extra columns - unblocking this ticket.
Azul will work on automation.
