### ISSUE TITLE
Optimus and Cell Ranger equivalent of cell_suspension_id

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/matrix-service#292]
For SS2 cell_suspendion_id is used to correlate the matrix service output file back to the manifest and metadata tsv files.
What field will be used for the Cell Ranger and Optimus pipelines?

**Comment by theathorn** [comment]
@briandoconnor  For 10x (Optimus & Cell Ranger) the (matrix service internal) cell_id is different from the cell_suspension.provenance.doc_id which *does* link to back to the manifest file.

For SS2 cell_id is the same as cell_suspension.provenance.doc_id but in general this should not be relied upon.

**Comment by brianraymor** [comment]
The cell_suspension.provenance.doc[ument]_id is already exposed. No work is required.
