### ISSUE TITLE
Generate per-project matrix output files in an S3 bucket for all projects in prod

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/matrix-service#293]
Generate one Matrix Service output file for each project (defined by the project uuid) and matrix output file format type (loom, csv, mtx, etc.) and store them in an S3 bucket according to the following specification:

~s3://url.data.humancellatlas.org/projects/$uuid.$extension~
http://url.data.humancellatlas.org/projects/ff481f29-3d0b-4533-9de2-a760c61c162d.loom

Putting the files in S3 is a short term solution until we can get a metadata-schema change to support different bundle types in (https://app.zenhub.com/workspace/o/humancellatlas/metadata-schema/issues/986).

**Comment by theathorn** [comment]
Blocking https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-browser/364

**Comment by mckinsel** [comment]
We have two of them in s3://hca-prepared-matrices

**Comment by theathorn** [comment]
@mckinsel to drop the project name from e.g. https://hca-prepared-matrices.s3.amazonaws.com/Single+cell+transcriptome+analysis+of+human+pancreas/63910278-7763-4aeb-8b3a-15c0e199abd2.csv.zip and Azul will then copy the files (initially by manually running a script; later by automation) to the Data Browser S3 bucket which also stores the metadata tsv files.

**Comment by mckinsel** [comment]
Project name has been replaced by uuid.

**Comment by brianraymor** [comment]
Closing in favor of [automating the process](https://github.com/HumanCellAtlas/matrix-service/issues/331).
