### ISSUE TITLE
[Spike] What does a query to Matrix Service look like?

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/matrix-service#3]
For the MVP, queries to the matrix service will mix a couple of different concepts. First, a query needs to tell the matrix service which matrix files in which bundles should be included in the response. Second, it needs to tell the matrix service how to filter those matrices (or not to filter them at all). We need to define how that's going to work.

AC:
Document that describes the query functionality of the matrix service MVP.

**Comment by l5han** [comment]
https://docs.google.com/document/d/1vHf1shvxmmUsCrbNWb8ABrEcQma2GKcQTSoPYDZ5vhY/edit?usp=sharing
