### ISSUE TITLE
Review Pangeo and Quilt

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#31]
**Estimate: 2 days**

Review [Pangeo](http://pangeo.io/) and [Quilt](https://quiltdata.com/)

**Comment by mckinsel** [comment]
The purpose of this ticket was to take a quick look over what's being done by Quilt, Pangeo, Bioconductor to see if there's anything we're doing that looks sharply incompatible, or if we're not taking advantage of some obviously superior design.

I looked through the code/interfaces for these and didn't see anything that suggests we need to make a change at this time.
