### ISSUE TITLE
Developer Feedback from Coding to the DCP

### ISSUE THREAD

**Issue by DailyDreaming** [HumanCellAtlas/matrix-service#322]
Summarizing some of my experience in attempting to use the API for the first time:
- It's unclear how to submit the `filter` param from the documentation.
- `"format": "zarr"` seems like it should be valid in a submission (see below).
- GET valid `filters` and `fields` return the exact same lists and it's unclear how these are different.
- The difference in the `v0` and `v1` endpoints don't seem to be explained.

To explain further, running a query, I was able to successfully submit a request, however the documentation does not seem to exist in constructing a "`filter`".  I constructed a working query by inspecting: https://github.com/HumanCellAtlas/matrix-service/blob/e76e1038cd388d6bc064ce95eea585a4923df82b/tests/functional/test_matrix_service.py#L406

It surprised me that the `zarr` file format is not accepted.  So this is invalid:

```
{
  "feature": "gene",
  "fields": [
    "genes_detected"
  ],
  "filter": {"op": "and",
                     "value": [
                         {"op": "=",
                          "field": "library_preparation_protocol.library_construction_method.ontology",
                          "value": "EFO:0008931"},
                         {"op": "!=",
                          "field": "derived_organ_label",
                          "value": "decidua"}]},
  "format": "zarr"
}
```

But removing the `"format": "zarr"` allows for a successful submission.  Also querying the valid formats does not return `zarr` (`curl -X GET "https://matrix.dev.data.humancellatlas.org/v1/formats" -H  "accept: application/json"`), which does not seem intuitive to me.

**Comment by brianraymor** [comment]
Currently, *Swagger UI supports example but currently does not support [**multiple examples**](https://github.com/swagger-api/swagger-ui/issues/2651)*. Here's a pointer to our [multiple examples](https://github.com/HumanCellAtlas/matrix-service/blob/master/config/matrix-api.yml#L125).

We also have vignettes in progress - https://github.com/HumanCellAtlas/matrix-service/pull/309

**Comment by DailyDreaming** [comment]
Zarr is still in the docs and should probably be removed and the mention that `loom` is the actual default now.

**Comment by maximilianh** [comment]
Hmm... why would it support zarr?
Should it support that ?

**Comment by brianraymor** [comment]
RE [zarr references](https://github.com/HumanCellAtlas/matrix-service/issues/322#issuecomment-503493112) - the unsupported format is listed in [README.md](https://github.com/HumanCellAtlas/matrix-service#file-formats).
