### ISSUE TITLE
Return raw values from the matrix service

### ISSUE THREAD

**Issue by mckinsel** [HumanCellAtlas/matrix-service#326]
Some users are going to have to do a lot of transformation from any of the formats that we might deliver, and they'd prefer to just use whatever output format is the fastest. That would be just zipping up the PSVs that redshift unloads to S3 and delivering them without any other transformation.

**Comment by brianraymor** [comment]
Per our July 9 discussion on performance (avoiding format conversion in this case), updating this issue to reflect _raw values_ which may be PSV(s) or other formats. We should also consider streaming smaller queries.

**Comment by brianraymor** [comment]
Per October 1 Matrix meeting, agreed that additional performance tasks were not required to meet SLA(s).
