### ISSUE TITLE
`total_umis` is a categorical variable in the loom output

### ISSUE THREAD

**Issue by mckinsel** [HumanCellAtlas/matrix-service#363]
That's not right.

Update: This is addressed in https://github.com/HumanCellAtlas/matrix-service/pull/379. The merge was paused until Marcus returns from vacation on September 10 due to potential impact on stability during the absence of both developers. Moving to Milestone 3.

**Comment by brianraymor** [comment]
This has been addressed in the improvements to format conversion. Will be validated and closed with that issue.
