### ISSUE TITLE
Unable to generate client for java via swagger-codegen

### ISSUE THREAD

**Issue by heuermh** [HumanCellAtlas/matrix-service#366]
See issue filed against swagger-codgen
https://github.com/swagger-api/swagger-codegen/issues/9636

**Comment by brianraymor** [comment]
@heuermh - Was this issue intended to be _informational_ rather than _actionable_ based on the issue opened in the swagger-codegen repo?

**Comment by heuermh** [comment]
I need to do more investigation, I don’t yet know if the error is due to something wrong in the API specification or with swagger-codegen.

**Comment by brianraymor** [comment]
@heuermh - Any further information? Also, what is the context for:

> Would it be possible to split the v0 and v1 endpoints to separate specifications?

For example, were you curious if it would mitigate your issue? It may be possible - we'd need to research the chalice implications in more detail but it's low priority at the moment.

**Comment by heuermh** [comment]
Excepting that I don't have any context around why things are this way, I find the `v0_` `v1_` prefixes on model names odd and not very RESTful.  The version is already in the request URI `/v1/matrix`.

**Comment by HugoMario** [comment]
hello @heuermh sorry for this delay, i can assign this issue to myself, but cant guarantee i'll work immediately, since i'm lack of time. However if you are willing to propose a PR i can help with reviewing and merging

**Comment by HugoMario** [comment]
sorry, wrong repo :)

**Comment by heuermh** [comment]
Fixed for me with commit https://github.com/heuermh/hca-matrix-service-client/commit/241dad2398aa67f11e088917c455d3ce9c7db8d5, which updates swagger-codegen-maven-plugin dependency version to 3.0.12.  Thank you, @HugoMario!
