### ISSUE TITLE
Re-enable matrix service in dcp-wide integration tests

### ISSUE THREAD

**Issue by calvinnhieu** [HumanCellAtlas/matrix-service#372]
- [x] update DSS subscription to:
    - [x] subscribe to only test bundles in each environment
    - ~specify supported metadata schema versions in JMESPath query~
    - [x] authorize via HMAC
- [x] re-enable DSS subscriptions via `dss_subscription.py`
- [ ] re-enable matrix service functional test in [dcp-wide integration tests](https://github.com/HumanCellAtlas/dcp/pull/516)

**Comment by parthshahva** [comment]
@calvinnhieu https://github.com/HumanCellAtlas/dcp/pull/485/files#diff-bcf9594365343a5aa07d273b9d26072fR133 should also be updated once this is in place. It would be nice to retrieve a matrix for the user's project during the tutorial

**Comment by calvinnhieu** [comment]
"specify supported metadata schema versions in JMESPath query" is no longer required as it is preferred that the DCP wide integration tests test the latest metadata schema versions against the matrix service.

**Comment by calvinnhieu** [comment]
Thanks for the ideas @parthshahva - will update tutorial once this lands. Can you confirm [this change](https://github.com/HumanCellAtlas/dcp/pull/516) re-enables the matrix service in scale tests as well?
