### ISSUE TITLE
[non-breaking] Updates to Optimus Outputs

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/matrix-service#377]
The Data Processing service will be updating the Optimus outputs in two key ways. 

(1) We are copying the EmptyDrops outputs into the Zarr object. We will be keeping the existing EmptyDrops outputs as well, so there is no need to change anything immediately. 

(2) We will be adding an option to output Loom format instead of Zarr. This will be optional and will not be "on" in production for the DCP, but we wanted to inform you in case it was of interest. We are not updating SS2 in the same way immediately, but will be later this year.

**Comment by mckinsel** [comment]
@barkasn and I talked about this on Monday. Nick is going to update the matrix_format_spec in skylab to reflect the code; it had gotten a little out of sync. The new zarr schema will require some changes in our ETL, but the pipelines team is going to give us some warning about when we should start seeing those bundles.

Also, the new zarr files from optimus have many more computed metadata fields than we currently expose in the matrix service. Nick was going to talk to @kbergin about how to prioritize curating that list (or possibly deciding it's all important and should be loaded into the matrix service).

**Comment by brianraymor** [comment]
Reviewed during our November 5 meeting. Agreed to close this _informational_ issue and open a new issue related to the exposing more/all computed analysis metadata.
