### ISSUE TITLE
Change human gencode annotation

### ISSUE THREAD

**Issue by mckinsel** [HumanCellAtlas/matrix-service#384]
In the matrix service, [we use](https://github.com/HumanCellAtlas/matrix-service/blob/master/matrix/common/etl/transformers/feature.py#L16-L17) the gencode v27 "comprehensive gene annotation on the reference chromosomes, scaffolds, assembly patches and alternate loci" for human data. 

I believe the pipelines use the "comprehensive gene annotation on the primary assembly" available here: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_27/gencode.v27.primary_assembly.annotation.gtf.gz .

The former is a superset of the latter, but it would be better if we were using the same annotation.

**Comment by brianraymor** [comment]
Double check PARY region.
