### ISSUE TITLE
Remediate High vulnerability

### ISSUE THREAD

**Issue by Lilalamar** [HumanCellAtlas/matrix-service#388]
Snyk reports 1 [**High** vulnerability](https://app.snyk.io/org/humancellatlas/project/025c084e-9099-4b27-a1ea-d370ff569f98) in HumanCellAtlas/matrix-service requirements.txt file. Please remediate by the end of Q3 Milestone 3 or, if applicable, document as a false positive finding.

**Comment by calvinnhieu** [comment]
The upgrade to numpy `1.17.0` in https://github.com/HumanCellAtlas/matrix-service/pull/379 resolves this issue.

Source:
https://github.com/numpy/numpy/releases/tag/v1.17.0rc1 (search for `np.load`)
