### ISSUE TITLE
Run Matrix Service for Reprogrammed_Dendritic_Cells

### ISSUE THREAD

**Issue by jychien** [HumanCellAtlas/matrix-service#396]
The Reprogrammed_Dendritic_Cells dataset is ready for Matrix Service.

This is a Barcelona incentive dataset and therefore high priority. 

Project title: Single cell profiling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts
Project short name: Reprogrammed_Dendritic_Cells
Project UUID: 116965f3-f094-4769-9d28-ae675c1b569c
Metadata: human, 10X V2
Bundles: 3 primary bundles

https://tracker.data.humancellatlas.org/?projectUUID=116965f3-f094-4769-9d28-ae675c1b569c

@HumanCellAtlas/data-ops

**Comment by calvinnhieu** [comment]
Hey @jychien, indexing failed due to the absence of `empty_drops_result.csv` in analysis bundles:

`cb88115c-75ef-4e8e-bbd7-a48e18960344.2019-09-26T120958.020808Z`
`52245757-73ba-43a2-a78d-0eba01cb4ce1.2019-09-26T120958.022205Z`
`1307154a-0396-4f2c-a1bf-4a2bf593b1a0.2019-09-26T120958.019770Z`

Matrix requires this file to process Optimus outputs. @HumanCellAtlas/pipelines-software-engineers-hornet could someone verify the file is missing?

**Comment by samanehsan** [comment]
Hey @calvinnhieu! I'll take a look

**Comment by jlzamanian** [comment]
@samanehsan 
It may be related to the information in this ticket.
https://github.com/DataBiosphere/azul/issues/1320
The analysis bundles also could not be indexed by Azul.

**Comment by parthshahva** [comment]
If this is only an issue with the updated analysis bundles and not the initial bundles created by workflows, this is likely to be an issue with the simple metadata update mechanism in Ingest.

**Comment by calvinnhieu** [comment]
Hm they don't seem to be present in the older versions either

**Comment by jlzamanian** [comment]
Yes. I am following up with ingest. 
The AUDR changes did update the primary bundles correctly, but this was probably the first attempt of AUDR simple update on a project with analysis bundles.

**Comment by samanehsan** [comment]
Looking at the raw analysis bundle metadata using this ES query, I see "empty_drops_result.csv" missing from the bundle manifests for the newer bundles, but not the old ones:
```
{
  "es_query": {
    "query": {
      "bool": { 
        "must": [
          {
            "match": {
              "files.project_json.provenance.document_id": "116965f3-f094-4769-9d28-ae675c1b569c"
            }
          },
          {
            "match": {
              "files.analysis_process_json.type.text": "analysis"
            }
          }
        ]
      }
    }
  }
}
```

**Comment by calvinnhieu** [comment]
@samanehsan Thanks for verifying! Yes, I was looking at the `bundles/uuid` endpoint as well.

@jlzamanian Please let us know if Matrix should go ahead with indexing the older set of bundles or wait for the analysis bundles to be regenerated with the updated metadata. Thanks!

**Comment by jlzamanian** [comment]
@calvinnhieu Please hold off on indexing and matrix generation for this project until the issue is resolved.

We will keep you updated.

MS does index on one of the fields that was updated, so the matrix service DB and matrices would be affected.

**Comment by jlzamanian** [comment]
@calvinnhieu 

This dataset has been updated and the updated analysis bundles are ready for indexing.

**Comment by calvinnhieu** [comment]
Great! Re-indexing...

**Comment by brianraymor** [comment]
Related [conversation](https://humancellatlas.slack.com/archives/CC9AR11T7/p1570208924084100) in **the-matrix-reloaded** slack channel ...

**Comment by calvinnhieu** [comment]
Due to the novel experiment structure of this project, this project will not be available via the matrix service in time for Barcelona.

See the conversation linked above and #405 for more details.
