### ISSUE TITLE
Run Matrix Service for SingleCellLiverLandscape

### ISSUE THREAD

**Issue by jychien** [HumanCellAtlas/matrix-service#397]
The SingleCellLiverLandscape is ready for Matrix Service.

Project title: Dissecting the human liver cellular landscape by single cell RNA-seq reveals novel intrahepatic monocyte/ macrophage populations
Project short name: SingleCellLiverLandscape
Project UUID: 4d6f6c96-2a83-43d8-8fe1-0f53bffd4674
Metadata: human, 10X V2
Bundles: 5 primary bundles

https://tracker.data.humancellatlas.org/?projectUUID=4d6f6c96-2a83-43d8-8fe1-0f53bffd4674

@HumanCellAtlas/data-ops

**Comment by calvinnhieu** [comment]
Indexing complete. Generating project matrices today.

**Comment by calvinnhieu** [comment]
Project matrices (3 formats) available via Data Browser: https://data.humancellatlas.org/explore/projects?filter=%5B%7B"facetName"%3A"fileFormat"%2C"terms"%3A%5B"matrix"%5D%7D%5D
