### ISSUE TITLE
Remove matrix for spatio-temporal kidney project

### ISSUE THREAD

**Issue by jahilton** [HumanCellAtlas/matrix-service#411]
It has been discovered that some data in this project should not have been released due to GDPR.
The project is being completely tombstoned and will be partially re-ingested, so new analysis will be processed and the matrix will be generated from that.

project uuid: abe1a013-af7a-45ed-8c26-f3793c24a1f4

deadline: Thu 10/31

**Comment by calvinnhieu** [comment]
- Removed all project related data in all environments
- *Cleared Matrix cache of project matrices
- Deleted project matrices from Data Browser (all formats)

The project has been removed from the Matrix Service except for one access pattern: *cached matrices containing a subset of bundles from this project have not been cleared as they are difficult to identify individually. In the coming week, the Matrix Service will be performing a full reindex in which we will invalidate the entire cache.

**Comment by mckinsel** [comment]
The cache has been invalidated, the previous version of this project is now entirely gone from the matrix service.
