### ISSUE TITLE
Port over zarr implementation from table testing, package into zip/s, and deploy via s3 bucket/s

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/matrix-service#42]
- [x] Port driver code
- [x] Port mapper code
- [ ] Port worker code
    - [ ] Convert DynamoDB StateTable to Step Functions
    - [ ] Access bundles via DSS instead of S3
- [ ] Port reducer code
- [ ] Add functional test (dependency: test data from @mckinsel 
- [ ] Spin up Integration and Staging environments

**Comment by brianraymor** [comment]
10/15 - Complete by 10/18 (in Staging)
